### ISSUE TITLE
R Installation fails

### ISSUE THREAD

**Issue by glensbo** [thierrymoudiki/mlsauce#9]
* mlsauce version: New installation **for R**
* Operating System: Mac Os 10.14.6

```R
library(devtools)
> devtools::install_github("thierrymoudiki/mlsauce/R-package")
Downloading GitHub repo thierrymoudiki/mlsauce@HEAD
✓  checking for file ‘/private/var/folders/pf/cbcn8vs50zb7vzmxblqqpxym0000gn/T/Rtmpb540IK/remotes33d38dfac5b/thierrymoudiki-mlsauce-68e391a/R-package/DESCRIPTION’ ...
─  preparing ‘mlsauce’:
✓  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘mlsauce_0.7.1.tar.gz’
   
* installing *source* package ‘mlsauce’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
sh: pip: command not found
Warning in system2(python, args) : error in running command
Error: package or namespace load failed for ‘mlsauce’:
 .onLoad failed in loadNamespace() for 'mlsauce', details:
  call: NULL
  error: Error removing package(s): 'mlsauce'
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/mlsauce’
Error: Failed to install 'mlsauce' from GitHub:
  (converted from warning) installation of package ‘/var/folders/pf/cbcn8vs50zb7vzmxblqqpxym0000gn/T//Rtmpb540IK/file33d64aca788/mlsauce_0.7.1.tar.gz’ had non-zero exit status
```
─ Session info ───────────────────────────────────────────────────────────────────────
 setting  value                                      
 version  R version 3.6.2 Patched (2020-02-09 r77786)
 os       macOS Mojave 10.14.6                       
 system   x86_64, darwin15.6.0                       
 ui       RStudio                                    
 language (EN)                                       
 collate  en_US.UTF-8                                
 ctype    en_US.UTF-8                                
 tz       Europe/Copenhagen                          
 date     2020-08-02

**Comment by thierrymoudiki** [comment]
@glensbo Please **mention that this is R**. Which version of R? 
Can I see the result of `print(session_info())` too?

**Comment by glensbo** [comment]
Thanks for your reply - do you need the list of packages as well? I have edited my post with the initial part of the session info

**Comment by thierrymoudiki** [comment]
@glensbo the whole output of `print(session_info())` could be helpful.

**Comment by glensbo** [comment]
Here it comes:
 print(session_info())
─ Session info ───────────────────────────────────────────────────────────────────────
 setting  value                                      
 version  R version 3.6.2 Patched (2020-02-09 r77786)
 os       macOS Mojave 10.14.6                       
 system   x86_64, darwin15.6.0                       
 ui       RStudio                                    
 language (EN)                                       
 collate  en_US.UTF-8                                
 ctype    en_US.UTF-8                                
 tz       Europe/Copenhagen                          
 date     2020-08-02                                 

─ Packages ───────────────────────────────────────────────────────────────────────────
 package     * version    date       lib source                             
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                     
 backports     1.1.8      2020-06-17 [1] CRAN (R 3.6.2)                     
 base64enc     0.1-3      2015-07-28 [1] CRAN (R 3.6.0)                     
 callr         3.4.3      2020-03-28 [1] CRAN (R 3.6.2)                     
 cli           2.0.2      2020-02-28 [1] CRAN (R 3.6.0)                     
 colorspace    1.4-1      2019-03-18 [1] CRAN (R 3.6.0)                     
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                     
 curl          4.3        2019-12-02 [1] CRAN (R 3.6.0)                     
 data.table    1.12.8     2019-12-09 [1] CRAN (R 3.6.0)                     
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                     
 devtools    * 2.3.1      2020-07-21 [1] CRAN (R 3.6.2)                     
 digest        0.6.25     2020-02-23 [1] CRAN (R 3.6.0)                     
 dplyr         1.0.0      2020-05-29 [1] CRAN (R 3.6.2)                     
 ellipsis      0.3.1      2020-05-15 [1] CRAN (R 3.6.2)                     
 evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                     
 fansi         0.4.1      2020-01-08 [1] CRAN (R 3.6.0)                     
 fs            1.4.2      2020-06-30 [1] CRAN (R 3.6.2)                     
 generics      0.0.2      2018-11-29 [1] CRAN (R 3.6.0)                     
 ggplot2       3.3.2      2020-06-19 [1] CRAN (R 3.6.2)                     
 glue          1.4.1      2020-05-13 [1] CRAN (R 3.6.2)                     
 gridExtra     2.3        2017-09-09 [1] CRAN (R 3.6.0)                     
 gtable        0.3.0      2019-03-25 [1] CRAN (R 3.6.0)                     
 htmltools     0.5.0      2020-06-16 [1] CRAN (R 3.6.2)                     
 jsonlite      1.7.0      2020-06-25 [1] CRAN (R 3.6.2)                     
 knitr         1.29       2020-06-23 [1] CRAN (R 3.6.2)                     
 lattice       0.20-41    2020-04-02 [1] CRAN (R 3.6.2)                     
 lifecycle     0.2.0      2020-03-06 [1] CRAN (R 3.6.0)                     
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.6.0)                     
 Matrix        1.2-18     2019-11-27 [1] CRAN (R 3.6.2)                     
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                     
 mgcv          1.8-31     2019-11-09 [1] CRAN (R 3.6.2)                     
 munsell       0.5.0      2018-06-12 [1] CRAN (R 3.6.0)                     
 nlme          3.1-148    2020-05-24 [1] CRAN (R 3.6.2)                     
 packrat       0.5.0      2018-11-14 [1] CRAN (R 3.6.0)                     
 pillar        1.4.6      2020-07-10 [1] CRAN (R 3.6.2)                     
 pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 3.6.2)                     
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 3.6.0)                     
 pkgload       1.1.0      2020-05-29 [1] CRAN (R 3.6.2)                     
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 3.6.0)                     
 processx      3.4.3      2020-07-05 [1] CRAN (R 3.6.2)                     
 ps            1.3.3      2020-05-08 [1] CRAN (R 3.6.2)                     
 purrr         0.3.4      2020-04-17 [1] CRAN (R 3.6.2)                     
 R6            2.4.1      2019-11-12 [1] CRAN (R 3.6.0)                     
 Rcpp          1.0.5      2020-07-06 [1] CRAN (R 3.6.2)                     
 remotes       2.2.0      2020-07-21 [1] CRAN (R 3.6.2)                     
 reticulate    1.16-9000  2020-08-02 [1] Github (rstudio/reticulate@e811aec)
 rlang         0.4.7      2020-07-09 [1] CRAN (R 3.6.2)                     
 rmarkdown     2.3.2      2020-07-10 [1] Github (rstudio/rmarkdown@ff1b279) 
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                     
 rqdatatable   1.2.7      2020-02-11 [1] CRAN (R 3.6.0)                     
 rquery        1.4.4      2020-02-18 [1] CRAN (R 3.6.0)                     
 rstudioapi    0.11       2020-02-07 [1] CRAN (R 3.6.0)                     
 scales        1.1.1      2020-05-11 [1] CRAN (R 3.6.2)                     
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                     
 sigr          1.0.6      2019-07-24 [1] CRAN (R 3.6.0)                     
 tensorflow    2.2.0.9000 2020-07-28 [1] Github (rstudio/tensorflow@4ed023a)
 testthat      2.3.2      2020-03-02 [1] CRAN (R 3.6.0)                     
 tfruns        1.4        2018-08-25 [1] CRAN (R 3.6.0)                     
 tibble        3.0.3      2020-07-10 [1] CRAN (R 3.6.2)                     
 tidyselect    1.1.0      2020-05-11 [1] CRAN (R 3.6.2)                     
 tinytex       0.25       2020-07-24 [1] CRAN (R 3.6.2)                     
 usethis     * 1.6.1      2020-04-29 [1] CRAN (R 3.6.2)                     
 vctrs         0.3.2      2020-07-15 [1] CRAN (R 3.6.2)                     
 whisker       0.4        2019-08-28 [1] CRAN (R 3.6.0)                     
 withr         2.2.0      2020-04-20 [1] CRAN (R 3.6.2)                     
 wrapr         2.0.0      2020-03-28 [1] CRAN (R 3.6.2)                     
 WVPlots       1.2.5      2020-05-01 [1] CRAN (R 3.6.2)                     
 xfun          0.16       2020-07-24 [1] CRAN (R 3.6.2)                     
 yaml          2.2.1      2020-02-01 [1] CRAN (R 3.6.0)

**Comment by thierrymoudiki** [comment]
@glensbo This might be the issue: https://github.com/rstudio/reticulate/issues/496
Will work on fixing this next week. Unless you want to give a try!

**Comment by glensbo** [comment]
mlsauce installed! Solution:
I have a messy phyton environment confusing RStudio - have had success (installing tensorflow) with these two lines before running anything else:
Sys.setenv(TENSORFLOW_PYTHON="/Users/MY_COMPUTER_NAME/opt/anaconda3/bin/")
tensorflow::install_tensorflow()

**Comment by glensbo** [comment]
Still got problems though - sh: pip: command not found
Error: package or namespace load failed for ‘mlsauce’:
 .onLoad failed in loadNamespace() for 'mlsauce', details:
  call: NULL
  error: Error removing package(s): 'mlsauce'

Will investigate and return if/when I find the solution

**Comment by thierrymoudiki** [comment]
Hi @glensbo. Please try again now. An example, from beginning to end. Ignore the warnings.

**Comment by glensbo** [comment]
Thanks - it works! got these results (With no other code than the provided from https://thierrymoudiki.github.io/blog/2020/07/24/python/misc/r/xai-boosting):
obj$fit(X_train, y_train)	
100%|██████████| 100/100 [00:00<00:00, 1276.35it/s]LSBoostClassifier(col_sample=1.0, dropout=0.0, row_sample=1.0)

> print(proc.time()[3] - start)
elapsed 
  9.157 
> start <- proc.time()[3]
> print(obj$score(X_test, y_test))
[1] 0.9253731
> print(proc.time()[3] - start)
elapsed 
  5.039 
> X <- as.matrix(datasets::mtcars[, -1])
> y <- as.integer(datasets::mtcars[, 1])
> n <- dim(X)[1]
> p <- dim(X)[2]
> set.seed(21341)
> train_index <- sample(x = 1:n, size = floor(0.8*n), replace = TRUE)
> test_index <- -train_index
> X_train <- as.matrix(X[train_index, ])
> y_train <- as.double(y[train_index])
> X_test <- as.matrix(X[test_index, ])
> y_test <- as.double(y[test_index])
> # using default parameters
> obj <- mlsauce::LSBoostRegressor()
> start <- proc.time()[3]
> obj$fit(X_train, y_train)
100%|██████████| 100/100 [00:00<00:00, 1357.87it/s]LSBoostRegressor(col_sample=1.0, dropout=0.0, row_sample=1.0)

> print(proc.time()[3] - start)
elapsed 
  5.214 
> start <- proc.time()[3]
> print(sqrt(mean((obj$predict(X_test) - y_test)**2)))
[1] 6.482376
> print(proc.time()[3] - start)
elapsed 
  2.463 
>

**Comment by glensbo** [comment]
And for the article here (https://thierrymoudiki.github.io//blog/2020/07/31/python/r/misc/xai-boosting-2) everything worked:

print(session_info())
─ Session info ───────────────────────────────────────────────────────────────────────
 setting  value                                      
 version  R version 3.6.2 Patched (2020-02-09 r77786)
 os       macOS Mojave 10.14.6                       
 system   x86_64, darwin15.6.0                       
 ui       RStudio                                    
 language (EN)                                       
 collate  en_US.UTF-8                                
 ctype    en_US.UTF-8                                
 tz       Europe/Copenhagen                          
 date     2020-08-03                                 

─ Packages ───────────────────────────────────────────────────────────────────────────
 package     * version   date       lib source                                 
 assertthat    0.2.1     2019-03-21 [1] CRAN (R 3.6.0)                         
 backports     1.1.8     2020-06-17 [1] CRAN (R 3.6.2)                         
 callr         3.4.3     2020-03-28 [1] CRAN (R 3.6.2)                         
 cli           2.0.2     2020-02-28 [1] CRAN (R 3.6.0)                         
 crayon        1.3.4     2017-09-16 [1] CRAN (R 3.6.0)                         
 curl          4.3       2019-12-02 [1] CRAN (R 3.6.0)                         
 desc          1.2.0     2018-05-01 [1] CRAN (R 3.6.0)                         
 devtools    * 2.3.1     2020-07-21 [1] CRAN (R 3.6.2)                         
 digest        0.6.25    2020-02-23 [1] CRAN (R 3.6.0)                         
 ellipsis      0.3.1     2020-05-15 [1] CRAN (R 3.6.2)                         
 evaluate      0.14      2019-05-28 [1] CRAN (R 3.6.0)                         
 fansi         0.4.1     2020-01-08 [1] CRAN (R 3.6.0)                         
 fs            1.4.2     2020-06-30 [1] CRAN (R 3.6.2)                         
 glue          1.4.1     2020-05-13 [1] CRAN (R 3.6.2)                         
 htmltools     0.5.0     2020-06-16 [1] CRAN (R 3.6.2)                         
 jsonlite      1.7.0     2020-06-25 [1] CRAN (R 3.6.2)                         
 knitr         1.29      2020-06-23 [1] CRAN (R 3.6.2)                         
 lattice       0.20-41   2020-04-02 [1] CRAN (R 3.6.2)                         
 magrittr      1.5       2014-11-22 [1] CRAN (R 3.6.0)                         
 Matrix        1.2-18    2019-11-27 [1] CRAN (R 3.6.2)                         
 memoise       1.1.0     2017-04-21 [1] CRAN (R 3.6.0)                         
 mlsauce     * 0.7.3     2020-08-03 [1] Github (thierrymoudiki/mlsauce@d1c6f16)
 packrat       0.5.0     2018-11-14 [1] CRAN (R 3.6.0)                         
 pkgbuild      1.1.0     2020-07-13 [1] CRAN (R 3.6.2)                         
 pkgload       1.1.0     2020-05-29 [1] CRAN (R 3.6.2)                         
 prettyunits   1.1.1     2020-01-24 [1] CRAN (R 3.6.0)                         
 processx      3.4.3     2020-07-05 [1] CRAN (R 3.6.2)                         
 ps            1.3.3     2020-05-08 [1] CRAN (R 3.6.2)                         
 R6            2.4.1     2019-11-12 [1] CRAN (R 3.6.0)                         
 rappdirs      0.3.1     2016-03-28 [1] CRAN (R 3.6.0)                         
 Rcpp          1.0.5     2020-07-06 [1] CRAN (R 3.6.2)                         
 remotes       2.2.0     2020-07-21 [1] CRAN (R 3.6.2)                         
 reticulate    1.16-9000 2020-08-02 [1] Github (rstudio/reticulate@e811aec)    
 rlang         0.4.7     2020-07-09 [1] CRAN (R 3.6.2)                         
 rmarkdown     2.3.2     2020-07-10 [1] Github (rstudio/rmarkdown@ff1b279)     
 rprojroot     1.3-2     2018-01-03 [1] CRAN (R 3.6.0)                         
 rstudioapi    0.11      2020-02-07 [1] CRAN (R 3.6.0)                         
 sessioninfo   1.1.1     2018-11-05 [1] CRAN (R 3.6.0)                         
 testthat      2.3.2     2020-03-02 [1] CRAN (R 3.6.0)                         
 usethis     * 1.6.1     2020-04-29 [1] CRAN (R 3.6.2)                         
 withr         2.2.0     2020-04-20 [1] CRAN (R 3.6.2)                         
 xfun          0.16      2020-07-24 [1] CRAN (R 3.6.2)                         
 yaml          2.2.1     2020-02-01 [1] CRAN (R 3.6.0)

**Comment by thierrymoudiki** [comment]
@glensbo Shall we close the issue now?

**Comment by glensbo** [comment]
Yes - and thanks for your help

**Comment by glensbo** [comment]
Closed
